--- 
- hosts: mywebservers 
  become: yes 
  tasks: 
  - name: install java on ubuntu 
    apt: 
     name: 
     state: present 
    when: ansible_os_family=="Debian" 
  - name: install java on redhat 
    dnf: 
      name: 
      state: present 
    when: ansible_os_family=="RedHat" 