--- 
- hosts: 172.31.0.247  
  become: yes 
  tasks: 
  - name: i want to execute linux command 
    command: hostname -f  
    register: myresult  

  - name: i want to see(display) first task result 
    debug:  
    msg: "{{myresult}}" 