--- 
- hosts: 172.31.38.96 
  become: yes 
  tasks: 
  - name: i want to create a folder 
    file:  
       path: /home/maha/myfolder 
       state: directory 

  - include_tasks: myfile.yml 

  - name: copy the file into node side  
    copy:  
      src: mytextfile 
      dest: /home/maha/myfolder  

  - name: i want to download internet file 
    get_url: 
        url: https://archive.apache.org/dist/tomcat/tomcat-10/v10.0.10/bin/apache-tomcat-10.0.10.tar.gz
        dest: /home/maha/myfolder/apache-tomcat-10.0.10.tar.gz 
        force_basic_auth: yes 

  - name: i want to install apache2 webserver 
    apt:  
      name: apache2 
      state: present  

  - name: i want to copy index file into node side 
    template: 
       src: myindex.j2 
       dest: /var/www/html/index.html 

