--- 
- hosts: 172.31.38.96 
  become: yes 
  tasks: 
  - name: i want to create a folder 
    files:  
       path: /home/maha/myfolder 
       state: directory 

  - name: i want to create a file 
    file:  
      path: /home/maha/myfolder/myfirstfile 
      state: touch  