--- 
- hosts: 172.31.38.96 
         172.31.0.247 
  become: yes 
  tasks: 
  - name: i want to create a folder 
    file:  
       path: /home/maha/myfolder 
       state: directory 

  - include_tasks: myfile.yml 

  - name: copy the file into node side  
    copy:  
      src: mytextfile 
      dest: /home/maha/myfolder