--- 
- name: download tomcat tar file 
  get_url: 
    url: https://repo1.maven.org/maven2/org/apache/tomcat/tomcat/9.0.55/tomcat-9.0.55.tar.gz
    dest: /home/maha/tomcat-9.0.55.tar.gz 
    force_basic_auth: yes
  
- name: create tomcat folder 
  file:   
    file: /opt/tomcat  
    state: directory  

- name: extract tar file 
  command: 
      cmd: tar -zvxf apache-tomcat-9.0.55.tar.gz -C /opt/tomcat script==1
      creates: /path/to/LICENSE 
